# Generated by Django 3.1.2 on 2020-11-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blogs')),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
